env:
  NODE_VERSION: '16'
  PACT_BROKER_FEATURES: publish_pacts_using_old_api

BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script:
    - scripts/install.sh
  test_script:
    - scripts/test.sh
  # audit_script:
  #   - scripts/audit.sh

linux_arm64_task: 
  arm_container:
    image: ubuntu:22.04
    cpu: 4
    memory: 12G
  setup_script: |
      bash <(curl -sL https://gist.github.com/KEINOS/7101f542be23e5048198e2a27c3cfda8/raw/install_ruby_rpi.sh) <<< $'y'
      source ~/.bashrc
      sudo git clone --depth=1 https://github.com/Homebrew/brew /opt/homebrew
      sudo chown -R $(whoami) /opt/homebrew
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
      source ~/.bashrc
      brew update --force --verbose
      brew --version

  << : *BUILD_TEST_TASK_TEMPLATE

# macosx_arm64_task: 
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-base:latest
#   << : *BUILD_TEST_TASK_TEMPLATE



