# env:
#   NODE_VERSION: '16'
#   PACT_BROKER_FEATURES: publish_pacts_using_old_api

# BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
#   arch_check_script:
#     - uname -am
#   install_script:
#     - chmod +x ./scripts/install.sh && ./scripts/install.sh
#   test_script:
#     - chmod +x ./scripts/test.sh && ./scripts/test.sh
#   audit_script:
#     - chmod +x ./scripts/audit.sh && scripts/audit.sh

# # linux_arm64_task: 
# #   arm_container:
# #     image: ubuntu:22.04
# #     cpu: 4
# #     memory: 12G
# #   env:
# #     PATH: "$HOME/.rbenv/bin;/opt/homebrew/bin/brew:$PATH"
# #   setup_script: |
# #       DEBIAN_FRONTEND=noninteractive \
# #       apt-get update \
# #       && apt-get install -y git curl sudo ca-certificates \
# #       && rm -rf /var/lib/apt/lists/*
# #       rvm list known
# #       curl -fsSL https://gist.githubusercontent.com/ryansch/ab306af869743643286a55c67c6866ab/raw/24d965a1e6be01a168c1dd62233502b519c4c6c7/install.sh | /bin/bash
# #       brew --version

# #   << : *BUILD_TEST_TASK_TEMPLATE

# macosx_arm64_task: 
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-base:latest
#   # pre_req_script:
#       # We need rosetta in order to run the x86_64 package
#       # - softwareupdate --install-rosetta --agree-to-license
#   << : *BUILD_TEST_TASK_TEMPLATE


