env:
  NODE_VERSION: '16'
  PACT_BROKER_FEATURES: publish_pacts_using_old_api

BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script:
    - scripts/install.sh
  test_script:
    - scripts/test.sh
  # audit_script:
  #   - scripts/audit.sh

linux_arm64_task: 
  arm_container:
    image: ubuntu:22.04
    cpu: 4
    memory: 12G
  env:
    PATH: "$HOME/.rbenv/bin;/opt/homebrew/bin/brew:$PATH"
  setup_script: |
      apt update -y
      apt install -y curl git

      # Check out rbenv into ~/.rbenv
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      echo -e "\nexport PATH="$HOME/.rbenv/bin:$PATH"" >> ~/.bashrc
      echo -e "\neval "$(rbenv init -)"" >> ~/.bashrc
      eval "$(rbenv init -)"
      source ~/.bashrc
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      #  See: https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
      apt update -y
      apt install -y \
        autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zlib1g-dev \
        libncurses5-dev libffi-dev libgdbm-dev
      rbenv install 2.6.8 --verbose
      rbenv global 2.6.8
      source ~/.bashrc

      git clone --depth=1 https://github.com/Homebrew/brew /opt/homebrew
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
      eval "$(/opt/homebrew/bin/brew shellenv)"
      source ~/.bashrc
      brew update --force --verbose
      brew --version

  << : *BUILD_TEST_TASK_TEMPLATE

# macosx_arm64_task: 
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-base:latest
#   << : *BUILD_TEST_TASK_TEMPLATE



