env:
  NODE_VERSION: '16'
  PACT_BROKER_FEATURES: publish_pacts_using_old_api

BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script:
    - scripts/install.sh
  test_script:
    - scripts/test.sh
  # audit_script:
  #   - scripts/audit.sh

linux_arm64_task: 
  arm_container:
    image: ubuntu:22.04
    cpu: 4
    memory: 12G
  setup_script: |
      # Time the install process
      START_TIME=$SECONDS
      # Check out rbenv into ~/.rbenv
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      # Add ~/.rbenv/bin to $PATH, enable shims and autocompletion
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
      echo -e "\n${String}" >> ~/.bashrc
      eval "${String}"
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      #  See: https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
      sudo apt update
      sudo apt install -y \
        autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zlib1g-dev \
        libncurses5-dev libffi-dev libgdbm-dev
      CONFIGURE_OPTS="--disable-install-doc --enable-shared" rbenv install 2.6.8 --verbose
      rbenv global 2.6.8
      echo "gem: --no-document" > ~/.gemrc
      ELAPSED_TIME=$(($SECONDS - $START_TIME))
      echo -e "\nFinished in $(($ELAPSED_TIME/60/60)) hr, $(($ELAPSED_TIME/60%60)) min, and $(($ELAPSED_TIME%60)) sec\n"
      source ~/.bashrc
      sudo git clone --depth=1 https://github.com/Homebrew/brew /opt/homebrew
      sudo chown -R $(whoami) /opt/homebrew
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
      source ~/.bashrc
      brew update --force --verbose
      brew --version

  << : *BUILD_TEST_TASK_TEMPLATE

# macosx_arm64_task: 
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-base:latest
#   << : *BUILD_TEST_TASK_TEMPLATE



