# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/cirruslabs/softnet"
  version "0.7.2"
  depends_on :macos
  depends_on "rust" => :build
  url "https://github.com/cirruslabs/softnet/archive/refs/heads/main.zip"
  sha256 "b337e4acf8318f694a077b3f4906768ee91534182e0984f64eb03e116d887e49"
  on_macos do
    def install
      system "cargo build --release"
      bin.install "target/release/softnet" => "softnet"
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
