name: Test pact-ruby-standalone linux versions

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        Formula: [
          pact-ruby-standalone-0.0.1,
          pact-ruby-standalone-1.0.0,
          pact-ruby-standalone-1.0.1,
          pact-ruby-standalone-1.1.0,
          pact-ruby-standalone-1.1.1,
          pact-ruby-standalone-1.1.2-alpha.1,
          pact-ruby-standalone-1.1.2,
          pact-ruby-standalone-1.10.0,
          pact-ruby-standalone-1.11.0,
          pact-ruby-standalone-1.12.0,
          pact-ruby-standalone-1.13.0,
          pact-ruby-standalone-1.14.0,
          pact-ruby-standalone-1.15.0,
          pact-ruby-standalone-1.16.0,
          pact-ruby-standalone-1.17.0,
          pact-ruby-standalone-1.17.1,
          pact-ruby-standalone-1.18.0,
          pact-ruby-standalone-1.19.0,
          pact-ruby-standalone-1.2.0,
          pact-ruby-standalone-1.2.1,
          pact-ruby-standalone-1.2.2,
          pact-ruby-standalone-1.2.3,
          pact-ruby-standalone-1.2.4,
          pact-ruby-standalone-1.2.5,
          pact-ruby-standalone-1.20.0,
          pact-ruby-standalone-1.21.0,
          pact-ruby-standalone-1.22.0,
          pact-ruby-standalone-1.22.1,
          pact-ruby-standalone-1.24.0,
          pact-ruby-standalone-1.25.0,
          pact-ruby-standalone-1.26.0,
          pact-ruby-standalone-1.27.0,
          pact-ruby-standalone-1.28.0,
          pact-ruby-standalone-1.29.0,
          pact-ruby-standalone-1.29.1,
          pact-ruby-standalone-1.29.2,
          pact-ruby-standalone-1.3.1,
          pact-ruby-standalone-1.30.0,
          pact-ruby-standalone-1.30.1,
          pact-ruby-standalone-1.31.0,
          pact-ruby-standalone-1.32.0,
          pact-ruby-standalone-1.33.0,
          pact-ruby-standalone-1.33.1,
          pact-ruby-standalone-1.34.0,
          pact-ruby-standalone-1.35.0,
          pact-ruby-standalone-1.36.0,
          pact-ruby-standalone-1.37.0,
          pact-ruby-standalone-1.38.0,
          pact-ruby-standalone-1.39.0,
          pact-ruby-standalone-1.4.2,
          pact-ruby-standalone-1.4.3,
          pact-ruby-standalone-1.4.4,
          pact-ruby-standalone-1.40.0,
          pact-ruby-standalone-1.41.0,
          pact-ruby-standalone-1.42.0,
          pact-ruby-standalone-1.43.0,
          pact-ruby-standalone-1.43.1,
          pact-ruby-standalone-1.44.0,
          pact-ruby-standalone-1.44.1,
          pact-ruby-standalone-1.44.2,
          pact-ruby-standalone-1.44.3,
          pact-ruby-standalone-1.45.0,
          pact-ruby-standalone-1.46.0,
          pact-ruby-standalone-1.47.0,
          pact-ruby-standalone-1.47.1,
          pact-ruby-standalone-1.47.2,
          pact-ruby-standalone-1.47.3,
          pact-ruby-standalone-1.48.0,
          pact-ruby-standalone-1.49.0,
          pact-ruby-standalone-1.5.0,
          pact-ruby-standalone-1.50.0,
          pact-ruby-standalone-1.50.1,
          pact-ruby-standalone-1.51.0,
          pact-ruby-standalone-1.52.0,
          pact-ruby-standalone-1.52.1,
          pact-ruby-standalone-1.52.2,
          pact-ruby-standalone-1.53.0,
          pact-ruby-standalone-1.54.0,
          pact-ruby-standalone-1.54.1,
          pact-ruby-standalone-1.54.2,
          pact-ruby-standalone-1.54.3,
          pact-ruby-standalone-1.54.4,
          pact-ruby-standalone-1.55.0,
          pact-ruby-standalone-1.56.0,
          pact-ruby-standalone-1.57.0,
          pact-ruby-standalone-1.58.0,
          pact-ruby-standalone-1.59.0,
          pact-ruby-standalone-1.6.0,
          pact-ruby-standalone-1.60.0,
          pact-ruby-standalone-1.61.0,
          pact-ruby-standalone-1.61.1,
          pact-ruby-standalone-1.61.2,
          pact-ruby-standalone-1.62.0,
          pact-ruby-standalone-1.63.0,
          pact-ruby-standalone-1.64.0,
          pact-ruby-standalone-1.64.1,
          pact-ruby-standalone-1.65.0,
          pact-ruby-standalone-1.65.1,
          pact-ruby-standalone-1.66.0,
          pact-ruby-standalone-1.67.0,
          pact-ruby-standalone-1.68.0,
          pact-ruby-standalone-1.69.0,
          pact-ruby-standalone-1.7.0,
          pact-ruby-standalone-1.7.1,
          pact-ruby-standalone-1.70.0,
          pact-ruby-standalone-1.70.2,
          pact-ruby-standalone-1.71.0,
          pact-ruby-standalone-1.72.0,
          pact-ruby-standalone-1.72.2,
          pact-ruby-standalone-1.73.0,
          pact-ruby-standalone-1.74.0,
          pact-ruby-standalone-1.75.0,
          pact-ruby-standalone-1.76.0,
          pact-ruby-standalone-1.76.1,
          pact-ruby-standalone-1.77.0,
          pact-ruby-standalone-1.78.0,
          pact-ruby-standalone-1.79.0,
          pact-ruby-standalone-1.8.0,
          pact-ruby-standalone-1.80.0,
          pact-ruby-standalone-1.80.1,
          pact-ruby-standalone-1.81.0,
          pact-ruby-standalone-1.82.0,
          pact-ruby-standalone-1.82.1,
          pact-ruby-standalone-1.82.2,
          pact-ruby-standalone-1.82.3,
          pact-ruby-standalone-1.83.0,
          pact-ruby-standalone-1.84.0,
          pact-ruby-standalone-1.85.0,
          pact-ruby-standalone-1.86.0,
          pact-ruby-standalone-1.87.2,
          pact-ruby-standalone-1.87.3,
          pact-ruby-standalone-1.87.4,
          pact-ruby-standalone-1.87.5,
          pact-ruby-standalone-1.87.6,
          pact-ruby-standalone-1.88.0,
          pact-ruby-standalone-1.88.1,
          pact-ruby-standalone-1.88.10,
          pact-ruby-standalone-1.88.11,
          pact-ruby-standalone-1.88.12,
          pact-ruby-standalone-1.88.13,
          pact-ruby-standalone-1.88.14,
          pact-ruby-standalone-1.88.15,
          pact-ruby-standalone-1.88.16,
          pact-ruby-standalone-1.88.17,
          pact-ruby-standalone-1.88.18,
          pact-ruby-standalone-1.88.19,
          pact-ruby-standalone-1.88.2,
          pact-ruby-standalone-1.88.20,
          pact-ruby-standalone-1.88.21,
          pact-ruby-standalone-1.88.22,
          pact-ruby-standalone-1.88.23,
          pact-ruby-standalone-1.88.24,
          pact-ruby-standalone-1.88.25,
          pact-ruby-standalone-1.88.26,
          pact-ruby-standalone-1.88.27,
          pact-ruby-standalone-1.88.28,
          pact-ruby-standalone-1.88.29,
          pact-ruby-standalone-1.88.3,
          pact-ruby-standalone-1.88.30,
          pact-ruby-standalone-1.88.31,
          pact-ruby-standalone-1.88.32,
          pact-ruby-standalone-1.88.33,
          pact-ruby-standalone-1.88.34,
          pact-ruby-standalone-1.88.35,
          pact-ruby-standalone-1.88.36,
          pact-ruby-standalone-1.88.37,
          pact-ruby-standalone-1.88.38,
          pact-ruby-standalone-1.88.39,
          pact-ruby-standalone-1.88.4,
          pact-ruby-standalone-1.88.40,
          pact-ruby-standalone-1.88.41,
          pact-ruby-standalone-1.88.42,
          pact-ruby-standalone-1.88.43,
          pact-ruby-standalone-1.88.44,
          pact-ruby-standalone-1.88.45,
          pact-ruby-standalone-1.88.46,
          pact-ruby-standalone-1.88.47,
          pact-ruby-standalone-1.88.48,
          pact-ruby-standalone-1.88.49,
          pact-ruby-standalone-1.88.5,
          pact-ruby-standalone-1.88.50,
          pact-ruby-standalone-1.88.51,
          pact-ruby-standalone-1.88.52,
          pact-ruby-standalone-1.88.53,
          pact-ruby-standalone-1.88.54,
          pact-ruby-standalone-1.88.55,
          pact-ruby-standalone-1.88.56,
          pact-ruby-standalone-1.88.57,
          pact-ruby-standalone-1.88.58,
          pact-ruby-standalone-1.88.59,
          pact-ruby-standalone-1.88.6,
          pact-ruby-standalone-1.88.60,
          pact-ruby-standalone-1.88.61,
          pact-ruby-standalone-1.88.62,
          pact-ruby-standalone-1.88.63,
          pact-ruby-standalone-1.88.64,
          pact-ruby-standalone-1.88.65,
          pact-ruby-standalone-1.88.66,
          pact-ruby-standalone-1.88.67,
          pact-ruby-standalone-1.88.68,
          pact-ruby-standalone-1.88.69,
          pact-ruby-standalone-1.88.7,
          pact-ruby-standalone-1.88.70,
          pact-ruby-standalone-1.88.71,
          pact-ruby-standalone-1.88.72,
          pact-ruby-standalone-1.88.73,
          pact-ruby-standalone-1.88.74,
          pact-ruby-standalone-1.88.75,
          pact-ruby-standalone-1.88.76,
          pact-ruby-standalone-1.88.77,
          pact-ruby-standalone-1.88.78,
          pact-ruby-standalone-1.88.79,
          pact-ruby-standalone-1.88.8,
          pact-ruby-standalone-1.88.80,
          pact-ruby-standalone-1.88.81,
          pact-ruby-standalone-1.88.82,
          pact-ruby-standalone-1.88.83,
          pact-ruby-standalone-1.88.84,
          pact-ruby-standalone-1.88.85,
          pact-ruby-standalone-1.88.86,
          pact-ruby-standalone-1.88.87,
          pact-ruby-standalone-1.88.88,
          pact-ruby-standalone-1.88.89,
          pact-ruby-standalone-1.88.9,
          pact-ruby-standalone-1.88.90,
          pact-ruby-standalone-1.88.91-rc1,
          pact-ruby-standalone-1.88.91-rc4,
          pact-ruby-standalone-1.88.91-rc5,
          pact-ruby-standalone-1.89.00,
          pact-ruby-standalone-1.89.01-rc1,
          pact-ruby-standalone-1.89.02-rc1,
          pact-ruby-standalone-1.9.0,
          pact-ruby-standalone-1.9.1,
          pact-ruby-standalone-1.90.0,
          pact-ruby-standalone-1.91.0,
          pact-ruby-standalone-1.92.0,
          pact-ruby-standalone-2.0.0,
          pact-ruby-standalone-2.2.0,
          pact-ruby-standalone-2.2.1,
          pact-ruby-standalone-untagged-ef26a461b62778ae4b47,
          pact-ruby-standalone
        ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        if: ${{ runner.os == 'Linux' }}

      - name: Install tap
        run: |
          brew install Formula/${{ matrix.Formula }}.rb

      - name: Brew test tap
        run: |
          brew test ${{ matrix.Formula }}