name: Test versions

on:
  # push:
  pull_request:

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [macOS-latest,ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        if: ${{ runner.os == 'Linux' }}

      - name: Install tap
        run: |
          brew tap you54f/pact
          brew install you54f/pact/pact-ruby-standalone

      - name: Brew test tap
        run: |
          brew test pact-ruby-standalone

      - name: Test tap
        run: |
          pact
          pact-broker --help
          pact-message --help
          pact-mock-service --help
          pact-plugin-cli --help
          pact-provider-verifier --help
          pact-stub-service --help
          pactflow --help
        

      - name: Audit tap (⚠️ experimental ⚠️) - so we ignore the error code 
        run: |
          brew audit --strict --online pact-ruby-standalone || true

